Iar 47/martin/allow commenting
green-fox-academy/IceAge-Reddit-Frontend pull request #15
Opened 2021-02-02 19:47 UTC by Karhalll

2021-02-11 19:21 UTC, AndyM22 approved these changes
👍

2021-02-15 15:01 UTC, SimProch requested changes

2021-02-15 16:39 UTC, Karhalll commented on src/app/components/authorized/post-details/post-details.component.html
> +        <div class="comment" *ngFor="let comment of post.comments.reverse()">
After some research i move showing comments in reverse order in SCSS file since it is matter of design.

2021-02-15 16:44 UTC, Karhalll commented on src/app/components/authorized/post-details/post-details.component.html
> +        <div class="comment" *ngFor="let comment of post.comments.reverse()">
That is true. But since this is in .html file the actuall post.comments in .ts file is intact.

2021-02-15 17:30 UTC, SimProch approved these changes

2021-02-15 17:31 UTC, merged